// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           pgtype.UUID `json:"id"`
	GoogleID     string      `json:"google_id"`
	Email        string      `json:"email"`
	Name         string      `json:"name"`
	ProfileImage pgtype.Text `json:"profile_image"`
}
