// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Blog struct {
	ID        pgtype.UUID        `json:"id"`
	Author    pgtype.UUID        `json:"author"`
	Title     string             `json:"title"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Version   int32              `json:"version"`
}

type BlogTag struct {
	BlogID pgtype.UUID `json:"blog_id"`
	TagID  pgtype.UUID `json:"tag_id"`
}

type Tag struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Version   int32              `json:"version"`
}

type User struct {
	ID           pgtype.UUID `json:"id"`
	GoogleID     string      `json:"google_id"`
	Email        string      `json:"email"`
	Name         string      `json:"name"`
	ProfileImage pgtype.Text `json:"profile_image"`
}
