// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddBlogTags(ctx context.Context, arg AddBlogTagsParams) error
	CreateBlog(ctx context.Context, arg CreateBlogParams) (Blog, error)
	CreateTag(ctx context.Context, name string) (Tag, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (pgtype.UUID, error)
	DeleteBlog(ctx context.Context, arg DeleteBlogParams) error
	DeleteTag(ctx context.Context, id pgtype.UUID) error
	GetBlogByID(ctx context.Context, id pgtype.UUID) (GetBlogByIDRow, error)
	GetBlogCount(ctx context.Context) (int64, error)
	GetBlogTags(ctx context.Context, blogID pgtype.UUID) ([]GetBlogTagsRow, error)
	GetBlogs(ctx context.Context, arg GetBlogsParams) ([]GetBlogsRow, error)
	GetTag(ctx context.Context, id pgtype.UUID) (Tag, error)
	GetTags(ctx context.Context, arg GetTagsParams) ([]Tag, error)
	GetTagsCount(ctx context.Context) (int64, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	RemoveBlogTags(ctx context.Context, blogID pgtype.UUID) error
	UpdateBlog(ctx context.Context, arg UpdateBlogParams) (Blog, error)
	UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
